UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Cafe/Bakery' WHERE name = 'Sweet Dutchess Kitchen & Cafe';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Wicked Eats Kitchen + Bar';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Bull and Barrel Pub';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'French/European' WHERE name = 'Chanterelle Bistro';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Vegan/Healthy' WHERE name = 'The Food Quotient';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Spirit Tree Estate Cidery';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'French/European' WHERE name = '16 Lakes Bistro';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Caribbean' WHERE name = 'Mealtors Jamaican Fusion Cuisine';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Italian' WHERE name = 'Rogues';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Shore Grill and Grotto';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Italian' WHERE name = 'Posta Italbar Cucina';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Italian' WHERE name = 'Ristorante Orsini';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Caribbean' WHERE name = 'Irie I Bistro';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Steakhouse' WHERE name = 'The Common Stove';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Picnic Snack Bar';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Seafood' WHERE name = 'Pier 21';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Seafood' WHERE name = 'World Famous Dock Lunch';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'American/Canadian' WHERE name = 'PORT Restaurant';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Persian/Asian' WHERE name = 'Chef Reza';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Cafe/Bakery' WHERE name = 'The Local Cafe and Restaurant';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Barrel Restaurant';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Blue Elephant Craft Brew House';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Cafe/Bakery' WHERE name = 'Aviv Immigrant Kitchen';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Italian' WHERE name = 'Detroit Pizzeria';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Then & Now Restaurant';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Italian' WHERE name = 'Lambretta Pizzeria';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = '360 The Restaurant at the CN Tower';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'French/European' WHERE name = 'Bindia Indian Bistro';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Richmond Station';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'DaiLo';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Magic Oven';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Maple Leaf Tavern';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'The Chef''s House';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Ted Rogers School of Management - Toronto Metropolitan University';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Ration Beverley';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Aleeza''s Pizza';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Urban Pantry';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Ay Caramba, Eh!';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'French/European' WHERE name = 'Bistro 67';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'The Springwood';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Westend Grill house';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Lumbertown Ale House';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'What The Fries';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'The Mill Restaurant & Pub';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'City Limits Bar & Grill';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'The Locker at the Falls';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'International/Fusion' WHERE name = 'Eganridge Resort, Golf Club & Spa';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Ste. Anne''s Spa';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Compass Grill & Bar';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Eclipse Restaurant & Terrace';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Maple Pub & Patio';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Steakhouse' WHERE name = 'The Antler Steakhouse';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'International/Fusion' WHERE name = 'Elmhirst''s Resort';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Seafood' WHERE name = 'Aquaterra';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Italian' WHERE name = 'Atomica';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Black Dog Tavern';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Seafood' WHERE name = 'Dianne''s Fishshack and Smokehouse';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Harper''s Burger Bar';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Cafe/Bakery' WHERE name = 'Toast & Jam';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Seafood' WHERE name = 'Wharf & Feather';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'French/European' WHERE name = 'The Works Burger Bistro';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'International/Fusion' WHERE name = 'Burleigh Falls Inn';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'International/Fusion' WHERE name = 'Heather Lodge';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Blue Cactus Bar and Grill';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Canadian Fine Dining' WHERE name = 'Beckta Dining & Wine';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'South Indian' WHERE name = 'Coconut Lagoon';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'SPIN Kitchen & Bar';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'The Publican House Brewery';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Cafe/Bakery' WHERE name = 'Blackhoney Bakery';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'The Waring House';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'The Royal Hotel';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Sand and Pearl Oyster Bar';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'The County Picnic';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Steakhouse' WHERE name = 'Tomasso''s Italian Grille';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Cafe/Bakery' WHERE name = 'New Grain Kitchen';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'North 46';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Trestle Brewing Company';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'The Breakfast Pig';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Verdicchio';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'The Gardens Gate';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Radical Gardens';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Ancaster Mill';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'River Road Brewing and Hops';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Winery/Wine Bar' WHERE name = 'The Restaurant at Redstone Winery';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Cowbell Brewing Co.';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'LA Roadhouse';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Mercasa Little Italy Eatery';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Steel Wheel Brewery';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Udderly Ridiculous';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Royal Botanical Gardens';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Spencer''s at the Waterfront';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Cambridge Mill';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Langdon Hall';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'International/Fusion' WHERE name = 'Little Mushroom Dining Lounge';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'French/European' WHERE name = 'Cascata Bistro';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Taste';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Crowsfoot';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Elora Mill';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'La Fontana';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Eddington''s of Exeter';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Cafe/Bakery' WHERE name = 'Robinson Fresh Cafe';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'French/European' WHERE name = 'Part 2 Bistro';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Borealis Grille and Bar';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Miijidaa';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Park Eatery';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'The Wooly Pub';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Wellington Brewery';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'French/European' WHERE name = 'Bistro 42';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Winery/Wine Bar' WHERE name = 'Oxley Estate Winery Restaurant';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'The Goose, Kitchen & Bar (formerly Jack''s Gastropub)';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Cafe/Bakery' WHERE name = 'Graffiti Market';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Rich Uncle Tavern';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Lancaster Smokehouse';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'odd duck';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'The Harvest Table';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Seafood' WHERE name = 'The Shoreline & Corbetta''s Woodfired Pizza at Summer House Park';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Cafe/Bakery' WHERE name = 'La Rose Specialty Foods and Fine Italian Bakery';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'French/European' WHERE name = 'Bistro Réunion';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Table Rock House Restaurant';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Legends on the Niagara';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Queen Victoria Place Restaurant';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Winery/Wine Bar' WHERE name = 'Peller Estates Winery Restaurant';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Queenston Heights Restaurant';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Cafe/Bakery' WHERE name = 'Kitchen76 at Two Sisters Vineyards';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'The Hungry Dragon';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Just Paellas';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Black Birch';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Deja Vu Diner';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'International/Fusion' WHERE name = 'The Mono Cliffs Inn';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Mudtown Station';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Italian' WHERE name = 'Bonfire on Queen';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'French/European' WHERE name = 'Maximilian Restaurant';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'David''s Restaurant';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Tutt Co.';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Cafe/Bakery' WHERE name = 'The Wellness Refinery';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Highview Food & Drink';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Windows On Rockway Restaurant';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Chartwell Group at Ridley College';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Steakhouse' WHERE name = 'Jacob''s Grill';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Cafe/Bakery' WHERE name = 'Stone Crock Bakery';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Cafe/Bakery' WHERE name = 'Butcher Market Food';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Cafe/Bakery' WHERE name = 'Symposium Cafe Restaurant & Lounge';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Stamp House Bed and Breakfast';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'French/European' WHERE name = 'Clock Tower Bistro';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Bruce Wine Bar';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = '18 Wheeler';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'Rose’s Family Restaurant';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Steakhouse' WHERE name = 'The Lincoln Grille';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Cafe/Bakery' WHERE name = 'Real Food Kitchen & Bake Shop';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Winery/Wine Bar' WHERE name = 'Vineland Estates Winery & Restaurant';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Eastern European' WHERE name = 'stuffed. Handcrafted Perogies';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'S & V Uptown';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'International/Fusion' WHERE name = 'M.T. Bellies';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'International/Fusion' WHERE name = 'University of Windsor - Residence Dining';
UPDATE public.restaurants SET price_tag = 'Cheap', cuisine_tag = 'Pub/Bar Food' WHERE name = 'Finkle Street Tap & Grill';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Farm-to-Table' WHERE name = 'SixThirtyNine';
UPDATE public.restaurants SET price_tag = 'Expensive', cuisine_tag = 'Winery/Wine Bar' WHERE name = 'Hessenland Inn & Schatz Winery';